# Generated by Django 2.1.2 on 2019-05-09 06:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_devnews_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='devnews',
            name='test',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='aaa'),
            preserve_default=False,
        ),
    ]
