# Generated by Django 2.1.2 on 2019-05-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_devnews_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devnews',
            name='test',
        ),
    ]
