# Generated by Django 2.1.2 on 2019-05-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_devnews_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DevNews',
            new_name='Post',
        ),
    ]
