# Generated by Django 2.1.2 on 2019-05-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190513_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Projects', 'Projects'), ('Study', 'Study'), ('Article', 'Article')], default='Study', max_length=10),
        ),
    ]
